apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-service'
        static_configs:
          - targets: ['node-service:3000']
      - job_name: 'python-grpc'
        static_configs:
          - targets: ['python-grpc:8000']
