import Colors from "@/constants/Colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      alignItems: "center",
    },
    platformBase: {
      width: 70,
      height: 70,
      backgroundColor: "#3D3D3D",
      transform: [{ rotateX: "45deg" }, { rotateZ: "0.785398rad" }],
      borderRadius: 5,
      position: "relative",
      justifyContent: "center",
      alignItems: "center",
    },
    platformBaseSupportRight: {
      width: 20,
      height: 15,
      transform: [{ rotateZ: "0.785398rad" }],
      position: "relative",
      borderRadius: 5,
      right: 34,
      bottom: -15,
      backgroundColor: "#3D3D3D",
    },
    platformBaseSupportLeft: {
      width: 20,
      height: 15,
      transform: [{ rotateZ: "0.785398rad" }],
      position: "relative",
      borderRadius: 5,
      left: 23,
      bottom: 26,
      backgroundColor: "#3D3D3D",
    },
    platformMiddle: {
      width: 70,
      height: 70,
      backgroundColor: "#ADADAD",
      borderRadius: 5,
      position: "absolute",
      top: -11,
      right: 11,
      justifyContent: "center",
      alignItems: "center",
    },
    platformTop: {
      width: 56,
      height: 56,
      backgroundColor: "#3D3D3D",
      borderRadius: 5,
      position: "absolute",
      top: 5,
      left: 5,
    },
    platformTopSupportRight: {
      width: 20,
      height: 15,
      transform: [{ rotateZ: "0.785398rad" }],
      position: "relative",
      borderRadius: 5,
      right: 7,
      bottom: -22,
      backgroundColor: "#3D3D3D",
    },
    platformTopSupportLeft: {
      width: 20,
      height: 15,
      transform: [{ rotateZ: "0.785398rad" }],
      position: "relative",
      borderRadius: 5,
      left: 32,
      bottom: 7,
      backgroundColor: "#3D3D3D",
    },
    platformTopOfTheTop: {
      width: 55,
      height: 55,
      backgroundColor: "#ADADAD",
      borderRadius: 5,
      position: "absolute",
      top: -8,
      right: 9,
      justifyContent: "center",
      alignItems: "center",
    },
    title: {
      marginTop: 5,
      justifyContent: "center",
      alignItems: "center",
      textAlign: "center",
      color: "#FFFFFF",
      fontSize: 18,
      fontWeight: "bold",
    },
  });
  

export default styles;
